version: "3"
services:
  web:
    build: WebAPI
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
