version: "3"
services:
  web:
    build: WebAPI
    restart: always
    ports:
      - "8000:8000"
    networks:
      - backend_network
      - db_network
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
    volumes:
      - ./WebAPI/core/schemas/scripts/db.sql:/docker-entrypoint-initdb.d/db.sql
      - db-data:/var/lib/postgresql/data
    networks:
      - db_network

  client:
    build: client
    restart: always
    environment:
      NUM_THREADS: 2
      MAX_DELAY_MS: 3000
    volumes:
      - ./client/logging.txt:/app/logging.txt
    networks:
      - backend_network
    depends_on:
      - web
    logging:
      driver: none

  background:
    build: background
    volumes:
      - ./background/logs.txt:/app/logs.txt
    restart: always
    networks:
      - backend_network
    depends_on:
      - db
      - web

volumes:
  db-data:

networks:
  db_network:
    driver: bridge

  backend_network:
    driver: bridge
